language: node_js

cache:
    yarn: true
    directories:
        - node_modules

before_script: yarn global add codecov

script:
    - yarn test --runInBand --coverage
    - yarn build

after_success: codecov --token=$CODECOV_TOKEN
